In [37]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
xls = pd.ExcelFile('ChatbotInteraction.xlsx')
df= pd.read_excel(xls)

In [6]:
df = df[df.Subj_ID != 21]

In [7]:
df = df[:-1].drop(['order'], axis=1)
df

,Subj_ID,responseType,Personality,Selfreported_cognitiveload,Friendly,Enjoyable,Helpful,Interesting,Satisfaction,Trust,Error,EngagementDuration
0,6.0,choice,agreeable,4.0,5.0,3.0,4.0,3.0,5.0,3.0,2.0,71.0
1,6.0,open,neutral,4.0,3.0,1.0,3.0,2.0,4.0,2.0,1.0,86.0
2,6.0,open,neutral,4.0,3.0,2.0,4.0,2.0,4.0,2.0,1.0,75.0
3,6.0,open,agreeable,4.0,5.0,5.0,5.0,5.0,4.0,4.0,3.0,117.0
4,6.0,choice,neutral,4.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...
131,24.0,choice,agreeable,4.0,4.0,4.0,4.0,5.0,4.0,4.0,0.0,113.0
132,24.0,open,agreeable,4.5,4.0,4.0,4.0,5.0,4.0,4.0,2.0,112.0
133,24.0,choice,neutral,3.5,3.0,3.0,4.0,4.0,4.0,4.0,0.0,140.0
134,24.0,choice,neutral,4.0,3.0,3.0,4.0,4.0,4.0,4.0,0.0,84.0
135,24.0,open,agreeable,4.5,5.0,4.0,5.0,5.0,5.0,5.0,1.0,115.0

In [8]:
df = df.groupby(['Subj_ID','responseType','Personality']).mean().reset_index()
df

,Subj_ID,responseType,Personality,Selfreported_cognitiveload,Friendly,Enjoyable,Helpful,Interesting,Satisfaction,Trust,Error,EngagementDuration
0,6.0,choice,agreeable,4.00,5.0,4.0,4.5,4.0,5.0,4.0,1.0,68.0
1,6.0,choice,neutral,4.00,4.5,4.5,5.0,4.5,5.0,4.5,0.5,57.5
2,6.0,open,agreeable,4.00,5.0,4.5,4.5,4.5,4.5,3.0,2.0,97.0
3,6.0,open,neutral,4.00,3.0,1.5,3.5,2.0,4.0,2.0,1.0,80.5
4,7.0,choice,agreeable,1.75,4.0,3.0,4.0,2.5,4.0,2.0,1.0,67.5
...,...,...,...,...,...,...,...,...,...,...,...,...
59,23.0,open,neutral,4.00,3.0,2.5,3.5,2.5,3.0,3.5,1.0,80.0
60,24.0,choice,agreeable,4.00,4.5,3.5,4.0,4.5,4.5,3.5,0.0,115.5
61,24.0,choice,neutral,3.75,3.0,3.0,4.0,4.0,4.0,4.0,0.0,112.0
62,24.0,open,agreeable,4.50,4.5,4.0,4.5,5.0,4.5,4.5,1.5,113.5
63,24.0,open,neutral,4.50,2.0,2.5,3.5,5.0,3.5,2.5,1.0,117.5

In [9]:
df.corr()

,Subj_ID,Selfreported_cognitiveload,Friendly,Enjoyable,Helpful,Interesting,Satisfaction,Trust,Error,EngagementDuration
Subj_ID,1.000000,0.231451,-0.279360,-0.191527,-0.308057,0.051446,-0.292655,0.036283,-0.109823,0.291858
Selfreported_cognitiveload,0.231451,1.000000,0.022200,-0.036449,-0.211839,0.217872,-0.137821,-0.061134,0.389165,0.309645
Friendly,-0.279360,0.022200,1.000000,0.840202,0.610999,0.640907,0.612977,0.319406,0.141898,-0.094785
Enjoyable,-0.191527,-0.036449,0.840202,1.000000,0.682280,0.612503,0.709784,0.515518,0.028679,-0.087876
Helpful,-0.308057,-0.211839,0.610999,0.682280,1.000000,0.375554,0.869212,0.526690,0.012673,-0.364635
Interesting,0.051446,0.217872,0.640907,0.612503,0.375554,1.000000,0.376084,0.289907,0.137376,0.175926
Satisfaction,-0.292655,-0.137821,0.612977,0.709784,0.869212,0.376084,1.000000,0.514331,0.053316,-0.333809
Trust,0.036283,-0.061134,0.319406,0.515518,0.526690,0.289907,0.514331,1.000000,-0.130018,-0.287662
Error,-0.109823,0.389165,0.141898,0.028679,0.012673,0.137376,0.053316,-0.130018,1.000000,0.119522
EngagementDuration,0.291858,0.309645,-0.094785,-0.087876,-0.364635,0.175926,-0.333809,-0.287662,0.119522,1.000000

In [10]:
df_open_agreeable = df[(df['responseType']=='open') & (df['Personality']=='agreeable')]
df_open_neutral = df[(df['responseType']=='open') & (df['Personality']=='neutral')]
df_choice_agreeable = df[(df['responseType']=='choice') & (df['Personality']=='agreeable')]
df_choice_neutral = df[(df['responseType']=='choice') & (df['Personality']=='neutral')]

In [11]:
len(df_open_agreeable)

16

In [12]:
len(df_open_neutral)

16

In [13]:
len(df_choice_agreeable)

16

In [14]:
len(df_choice_neutral)

16

In [15]:
df_mean = df_open_agreeable.mean().to_frame() + df_open_neutral.mean().to_frame() + df_choice_agreeable.mean().to_frame() + df_choice_neutral.mean().to_frame()

In [16]:
df_mean['open_agreeable'] = df_open_agreeable.mean().to_frame()
df_mean['open_neutral'] = df_open_neutral.mean().to_frame()
df_mean['choice_agreeable'] = df_choice_agreeable.mean().to_frame()
df_mean['choice_neutral'] = df_choice_neutral.mean().to_frame()

In [17]:
df_mean

,0,open_agreeable,open_neutral,choice_agreeable,choice_neutral
Subj_ID,59.75000,14.937500,14.937500,14.93750,14.93750
Selfreported_cognitiveload,14.78125,4.046875,4.015625,3.46875,3.25000
Friendly,14.90625,4.125000,2.968750,4.21875,3.59375
Enjoyable,13.71875,3.593750,2.812500,3.81250,3.50000
Helpful,16.18750,4.062500,3.687500,4.15625,4.28125
Interesting,12.75000,3.656250,2.500000,3.68750,2.90625
Satisfaction,16.18750,4.031250,3.718750,4.25000,4.18750
Trust,13.93750,3.593750,3.125000,3.50000,3.71875
Error,3.81250,1.593750,1.187500,0.84375,0.18750
EngagementDuration,337.93750,104.687500,79.312500,79.59375,74.34375

In [18]:
df_std = df_open_agreeable.std().to_frame() + df_open_neutral.std().to_frame() + df_choice_agreeable.std().to_frame() + df_choice_neutral.std().to_frame()
df_std['open_agreeable'] = df_open_agreeable.std().to_frame()
df_std['open_neutral'] = df_open_neutral.std().to_frame()
df_std['choice_agreeable'] = df_choice_agreeable.std().to_frame()
df_std['choice_neutral'] = df_choice_neutral.std().to_frame()
df_std

,0,open_agreeable,open_neutral,choice_agreeable,choice_neutral
Subj_ID,23.299499,5.824875,5.824875,5.824875,5.824875
Selfreported_cognitiveload,2.393230,0.400195,0.381540,0.789910,0.821584
Friendly,3.172676,0.695222,0.826009,0.893845,0.757600
Enjoyable,3.758555,0.860596,1.046821,1.014479,0.836660
Helpful,2.628472,0.655108,0.680074,0.746520,0.546771
Interesting,3.585928,0.850857,1.080123,0.813941,0.841006
Satisfaction,3.080094,0.805580,0.657489,0.912871,0.704154
Trust,4.287036,1.143369,1.040833,1.154701,0.948134
Error,1.930502,0.663796,0.359398,0.597739,0.309570
EngagementDuration,101.078116,43.529253,15.500403,22.184994,19.863466

In [19]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import AnovaRM
import pingouin as pg

In [20]:
#Selfreported_cognitiveload, Friendly, Enjoyable, Helpful, Interesting, Satisfaction, Trust, Error

In [21]:
res = pg.rm_anova(dv='Selfreported_cognitiveload', within=['responseType','Personality'], subject='Subj_ID', 
                  data=df, detailed=True)
res

,Source,SS,ddof1,ddof2,MS,F,p-unc,p-GG-corr,ng2,eps
0,responseType,7.222656,1,15,7.222656,16.758308,0.000958,0.000958,0.230808,1.0
1,Personality,0.250000,1,15,0.250000,1.276596,0.276277,0.276277,0.010279,1.0
2,responseType * Personality,0.140625,1,15,0.140625,1.097561,0.311390,0.311390,0.005808,1.0

In [22]:
#post-hoc test
post_hocs = pg.pairwise_ttests(dv='Selfreported_cognitiveload', within=['responseType','Personality'], subject='Subj_ID', padjust='fdr_bh', data=df)
post_hocs

/Users/xuhan/opt/anaconda3/lib/python3.8/site-packages/pingouin/pairwise.py:27: UserWarning: pairwise_ttests is deprecated, use pairwise_tests instead.
  warnings.warn("pairwise_ttests is deprecated, use pairwise_tests instead.", UserWarning)

,Contrast,responseType,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,responseType,-,choice,open,True,True,-4.093691,15.0,two-sided,0.000958,NaN,NaN,39.684,-1.157446
1,Personality,-,agreeable,neutral,True,True,1.129865,15.0,two-sided,0.276277,NaN,NaN,0.441,0.238327
2,responseType * Personality,choice,agreeable,neutral,True,True,1.259950,15.0,two-sided,0.226938,0.453876,fdr_bh,0.501,0.264592
3,responseType * Personality,open,agreeable,neutral,True,True,0.307148,15.0,two-sided,0.762954,0.762954,fdr_bh,0.266,0.077913

In [23]:
res = pg.rm_anova(dv='Friendly', within=['responseType','Personality'], subject='Subj_ID', 
                  data=df, detailed=True)
res

,Source,SS,ddof1,ddof2,MS,F,p-unc,p-GG-corr,ng2,eps
0,responseType,2.066406,1,15,2.066406,6.530864,0.021955,0.021955,0.051474,1.0
1,Personality,12.691406,1,15,12.691406,24.186104,0.000186,0.000186,0.249981,1.0
2,responseType * Personality,1.128906,1,15,1.128906,4.597031,0.048820,0.048820,0.028793,1.0

In [24]:
#post-hoc test
post_hocs = pg.pairwise_ttests(dv='Friendly', within=['responseType','Personality'], subject='Subj_ID', padjust='fdr_bh', data=df)
post_hocs

/Users/xuhan/opt/anaconda3/lib/python3.8/site-packages/pingouin/pairwise.py:27: UserWarning: pairwise_ttests is deprecated, use pairwise_tests instead.
  warnings.warn("pairwise_ttests is deprecated, use pairwise_tests instead.", UserWarning)

,Contrast,responseType,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,responseType,-,choice,open,True,True,2.555556,15.0,two-sided,0.021955,NaN,NaN,2.881,0.526890
1,Personality,-,agreeable,neutral,True,True,4.917937,15.0,two-sided,0.000186,NaN,NaN,165.399,1.235039
2,responseType * Personality,choice,agreeable,neutral,True,True,3.478042,15.0,two-sided,0.003372,0.003372,fdr_bh,13.56,0.735333
3,responseType * Personality,open,agreeable,neutral,True,True,4.570572,15.0,two-sided,0.000368,0.000736,fdr_bh,90.998,1.476381

In [25]:
res = pg.rm_anova(dv='Enjoyable', within=['responseType','Personality'], subject='Subj_ID', 
                  data=df, detailed=True)
res

,Source,SS,ddof1,ddof2,MS,F,p-unc,p-GG-corr,ng2,eps
0,responseType,3.285156,1,15,3.285156,4.976331,0.041387,0.041387,0.057868,1.0
1,Personality,4.785156,1,15,4.785156,7.633984,0.014503,0.014503,0.082121,1.0
2,responseType * Personality,0.878906,1,15,0.878906,1.867737,0.191871,0.191871,0.016167,1.0

In [26]:
#post-hoc test
post_hocs = pg.pairwise_ttests(dv='Enjoyable', within=['responseType','Personality'], subject='Subj_ID', padjust='fdr_bh', data=df)
post_hocs

/Users/xuhan/opt/anaconda3/lib/python3.8/site-packages/pingouin/pairwise.py:27: UserWarning: pairwise_ttests is deprecated, use pairwise_tests instead.
  warnings.warn("pairwise_ttests is deprecated, use pairwise_tests instead.", UserWarning)

,Contrast,responseType,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,responseType,-,choice,open,True,True,2.230769,15.0,two-sided,0.041387,NaN,NaN,1.742,0.562298
1,Personality,-,agreeable,neutral,True,True,2.762967,15.0,two-sided,0.014503,NaN,NaN,4.032,0.683265
2,responseType * Personality,choice,agreeable,neutral,True,True,1.619376,15.0,two-sided,0.126195,0.126195,fdr_bh,0.751,0.327610
3,responseType * Personality,open,agreeable,neutral,True,True,2.471334,15.0,two-sided,0.025930,0.051861,fdr_bh,2.521,0.794741

In [27]:
res = pg.rm_anova(dv='Helpful', within=['responseType','Personality'], subject='Subj_ID', 
                  data=df, detailed=True)
res

,Source,SS,ddof1,ddof2,MS,F,p-unc,p-GG-corr,ng2,eps
0,responseType,1.890625,1,15,1.890625,8.441860,0.010873,0.010873,0.067260,1.0
1,Personality,0.250000,1,15,0.250000,2.142857,0.163876,0.163876,0.009445,1.0
2,responseType * Personality,1.000000,1,15,1.000000,3.529412,0.079865,0.079865,0.036739,1.0

In [28]:
#post-hoc test
post_hocs = pg.pairwise_ttests(dv='Helpful', within=['responseType','Personality'], subject='Subj_ID', padjust='fdr_bh', data=df)
post_hocs

/Users/xuhan/opt/anaconda3/lib/python3.8/site-packages/pingouin/pairwise.py:27: UserWarning: pairwise_ttests is deprecated, use pairwise_tests instead.
  warnings.warn("pairwise_ttests is deprecated, use pairwise_tests instead.", UserWarning)

,Contrast,responseType,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,responseType,-,choice,open,True,True,2.905488,15.0,two-sided,0.010873,NaN,NaN,5.105,0.577234
1,Personality,-,agreeable,neutral,True,True,1.463850,15.0,two-sided,0.163876,NaN,NaN,0.624,0.218792
2,responseType * Personality,choice,agreeable,neutral,True,True,-0.807573,15.0,two-sided,0.431957,0.431957,fdr_bh,0.34,-0.186224
3,responseType * Personality,open,agreeable,neutral,True,True,2.323790,15.0,two-sided,0.034594,0.069188,fdr_bh,2.005,0.547465

In [29]:
res = pg.rm_anova(dv='Interesting', within=['responseType','Personality'], subject='Subj_ID', 
                  data=df, detailed=True)
res

,Source,SS,ddof1,ddof2,MS,F,p-unc,p-GG-corr,ng2,eps
0,responseType,0.765625,1,15,0.765625,2.882353,0.110198,0.110198,0.015414,1.0
1,Personality,15.015625,1,15,15.015625,13.873917,0.002033,0.002033,0.234906,1.0
2,responseType * Personality,0.562500,1,15,0.562500,1.216216,0.287484,0.287484,0.011371,1.0

In [30]:
#post-hoc test
post_hocs = pg.pairwise_ttests(dv='Interesting', within=['responseType','Personality'], subject='Subj_ID', padjust='fdr_bh', data=df)
post_hocs

/Users/xuhan/opt/anaconda3/lib/python3.8/site-packages/pingouin/pairwise.py:27: UserWarning: pairwise_ttests is deprecated, use pairwise_tests instead.
  warnings.warn("pairwise_ttests is deprecated, use pairwise_tests instead.", UserWarning)

,Contrast,responseType,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,responseType,-,choice,open,True,True,1.697749,15.0,two-sided,0.110198,NaN,NaN,0.829,0.325595
1,Personality,-,agreeable,neutral,True,True,3.724771,15.0,two-sided,0.002033,NaN,NaN,20.831,1.186850
2,responseType * Personality,choice,agreeable,neutral,True,True,3.075734,15.0,two-sided,0.007689,0.007689,fdr_bh,6.798,0.920214
3,responseType * Personality,open,agreeable,neutral,True,True,3.224511,15.0,two-sided,0.005672,0.007689,fdr_bh,8.759,1.159245

In [31]:
res = pg.rm_anova(dv='Satisfaction', within=['responseType','Personality'], subject='Subj_ID', 
                  data=df, detailed=True)
res

,Source,SS,ddof1,ddof2,MS,F,p-unc,p-GG-corr,ng2,eps
0,responseType,1.890625,1,15,1.890625,7.117647,0.017552,0.017552,0.049692,1.0
1,Personality,0.562500,1,15,0.562500,2.547170,0.131341,0.131341,0.015319,1.0
2,responseType * Personality,0.250000,1,15,0.250000,0.967742,0.340846,0.340846,0.006867,1.0

In [32]:
#post-hoc test
post_hocs = pg.pairwise_ttests(dv='Satisfaction', within=['responseType','Personality'], subject='Subj_ID', padjust='fdr_bh', data=df)
post_hocs

/Users/xuhan/opt/anaconda3/lib/python3.8/site-packages/pingouin/pairwise.py:27: UserWarning: pairwise_ttests is deprecated, use pairwise_tests instead.
  warnings.warn("pairwise_ttests is deprecated, use pairwise_tests instead.", UserWarning)

,Contrast,responseType,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,responseType,-,choice,open,True,True,2.667892,15.0,two-sided,0.017552,NaN,NaN,3.452,0.482241
1,Personality,-,agreeable,neutral,True,True,1.595986,15.0,two-sided,0.131341,NaN,NaN,0.73,0.266145
2,responseType * Personality,choice,agreeable,neutral,True,True,0.459639,15.0,two-sided,0.652367,0.652367,fdr_bh,0.28,0.074734
3,responseType * Personality,open,agreeable,neutral,True,True,1.535738,15.0,two-sided,0.145425,0.290849,fdr_bh,0.679,0.414298

In [33]:
res = pg.rm_anova(dv='Trust', within=['responseType','Personality'], subject='Subj_ID', 
                  data=df, detailed=True)
res

,Source,SS,ddof1,ddof2,MS,F,p-unc,p-GG-corr,ng2,eps
0,responseType,1.000000,1,15,1.000000,3.076923,0.099812,0.099812,0.014216,1.0
1,Personality,0.250000,1,15,0.250000,0.967742,0.340846,0.340846,0.003592,1.0
2,responseType * Personality,1.890625,1,15,1.890625,8.768116,0.009712,0.009712,0.026541,1.0

In [34]:
#post-hoc test
post_hocs = pg.pairwise_ttests(dv='Trust', within=['responseType','Personality'], subject='Subj_ID', padjust='fdr_bh', data=df)
post_hocs

/Users/xuhan/opt/anaconda3/lib/python3.8/site-packages/pingouin/pairwise.py:27: UserWarning: pairwise_ttests is deprecated, use pairwise_tests instead.
  warnings.warn("pairwise_ttests is deprecated, use pairwise_tests instead.", UserWarning)

,Contrast,responseType,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,responseType,-,choice,open,True,True,1.754116,15.0,two-sided,0.099812,NaN,NaN,0.891,0.239283
1,Personality,-,agreeable,neutral,True,True,0.983739,15.0,two-sided,0.340846,NaN,NaN,0.388,0.120614
2,responseType * Personality,choice,agreeable,neutral,True,True,-1.330821,15.0,two-sided,0.203125,0.203125,fdr_bh,0.539,-0.201836
3,responseType * Personality,open,agreeable,neutral,True,True,2.611165,15.0,two-sided,0.019657,0.039314,fdr_bh,3.15,0.417938

In [35]:
res = pg.rm_anova(dv='Error', within=['responseType','Personality'], subject='Subj_ID', 
                  data=df, detailed=True)
res

,Source,SS,ddof1,ddof2,MS,F,p-unc,p-GG-corr,ng2,eps
0,responseType,12.250000,1,15,12.250000,77.368421,2.627633e-07,2.627633e-07,0.443941,1.0
1,Personality,4.515625,1,15,4.515625,20.162791,4.315632e-04,4.315632e-04,0.227380,1.0
2,responseType * Personality,0.250000,1,15,0.250000,1.764706,2.038965e-01,2.038965e-01,0.016032,1.0

In [36]:
#post-hoc test
post_hocs = pg.pairwise_ttests(dv='Error', within=['responseType','Personality'], subject='Subj_ID', padjust='fdr_bh', data=df)
post_hocs

/Users/xuhan/opt/anaconda3/lib/python3.8/site-packages/pingouin/pairwise.py:27: UserWarning: pairwise_ttests is deprecated, use pairwise_tests instead.
  warnings.warn("pairwise_ttests is deprecated, use pairwise_tests instead.", UserWarning)

,Contrast,responseType,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,responseType,-,choice,open,True,True,-8.795932,15.0,two-sided,2.627633e-07,NaN,NaN,5.942e+04,-2.104118
1,Personality,-,agreeable,neutral,True,True,4.490300,15.0,two-sided,4.315632e-04,NaN,NaN,79.183,1.218136
2,responseType * Personality,choice,agreeable,neutral,True,True,3.881796,15.0,two-sided,1.475006e-03,0.002950,fdr_bh,27.403,1.343960
3,responseType * Personality,open,agreeable,neutral,True,True,3.104639,15.0,two-sided,7.248216e-03,0.007248,fdr_bh,7.14,0.741927